# Generated by Django 4.2 on 2023-05-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to='uploads/blog')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('cin', models.CharField(max_length=10)),
                ('permis', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=50)),
                ('boitVitesse', models.CharField(choices=[('A', 'Automatique'), ('M', 'Manuel')], max_length=20)),
                ('climatiseur', models.CharField(choices=[('O', 'OUI'), ('N', 'NON')], max_length=20)),
                ('carburant', models.CharField(choices=[('ES', 'Essence'), ('GA', 'Gasoil'), ('HY', 'Hybride')], max_length=20)),
                ('nombrePlace', models.IntegerField(blank=True, default=5)),
                ('nombrePort', models.IntegerField(blank=True, default=5, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=2)),
                ('image', models.ImageField(null=True, upload_to='uploads/vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField(auto_now_add=True, null=True)),
                ('dateFin', models.DateField(auto_now_add=True, null=True)),
                ('depart', models.CharField(max_length=100)),
                ('retour', models.CharField(max_length=100)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationVoiture.client')),
                ('Vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationVoiture.vehicule')),
            ],
        ),
    ]
