# Generated by Django 4.2 on 2023-05-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationVoiture', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='boitVitesse',
            field=models.CharField(choices=[('Automatique', 'Automatique'), ('Manuel', 'Manuel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='carburant',
            field=models.CharField(choices=[('Essence', 'Essence'), ('Gasoil', 'Gasoil'), ('Hybride', 'Hybride')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='climatiseur',
            field=models.CharField(choices=[('Climatisée', 'Climatisée'), ('N-Climatisée', 'N-Climatisée')], max_length=20),
        ),
    ]
