# Generated by Django 4.2 on 2023-05-21 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationVoiture', '0003_alter_vehicule_boitvitesse_alter_vehicule_carburant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='nombrePlace',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='nombrePort',
        ),
    ]
