# Generated by Django 4.2 on 2023-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationVoiture', '0007_alter_vehicule_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='permis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
    ]
