# Generated by Django 4.2 on 2023-05-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationVoiture', '0008_alter_client_cin_alter_client_permis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dateDebut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateFin',
            field=models.DateField(null=True),
        ),
    ]
